stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
    - data/raw
    - scripts/preprocess.py
    outs:
    - data/processed.csv
  train:
    cmd: python scripts/train.py
    deps:
    - data/processed.csv
    - scripts/train.py
    outs:
    - models/model_v1
